// This file is autogenerated by './gen.rb'. Do not edit.

#include "kern/methods.h"
#include "sys/syscall.h"

__attribute__ ((weak)) message_info_t
CNode_Copy (cte_t *, word_t, uint8_t, cte_t *, word_t, uint8_t, cap_rights_t)
{
  err_printf ("unimplemented kernel method CNode_Copy\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
CNode_Delete (cte_t *, word_t, uint8_t)
{
  err_printf ("unimplemented kernel method CNode_Delete\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
CNode_Mint (cte_t *, word_t, uint8_t, cte_t *, word_t, uint8_t, cap_rights_t,
            word_t)
{
  err_printf ("unimplemented kernel method CNode_Mint\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
CNode_Revoke (cte_t *, word_t, uint8_t)
{
  err_printf ("unimplemented kernel method CNode_Revoke\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
CNode_DebugPrint (cte_t *)
{
  err_printf ("unimplemented kernel method CNode_DebugPrint\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_Configure (cte_t *, word_t, cte_t *, word_t, cte_t *, word_t, word_t,
               cte_t *)
{
  err_printf ("unimplemented kernel method TCB_Configure\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_CopyRegisters (cte_t *, cte_t *, bool, bool, bool, bool, word_t)
{
  err_printf ("unimplemented kernel method TCB_CopyRegisters\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_ReadRegisters (cte_t *, bool, word_t, word_t, user_context_t *)
{
  err_printf ("unimplemented kernel method TCB_ReadRegisters\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_Resume (cte_t *)
{
  err_printf ("unimplemented kernel method TCB_Resume\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_BindNotification (cte_t *, cte_t *)
{
  err_printf ("unimplemented kernel method TCB_BindNotification\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_SetAffinity (cte_t *, word_t)
{
  err_printf ("unimplemented kernel method TCB_SetAffinity\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_SetIPCBuffer (cte_t *, word_t, cte_t *)
{
  err_printf ("unimplemented kernel method TCB_SetIPCBuffer\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_SetSpace (cte_t *, word_t, cte_t *, word_t, cte_t *, word_t)
{
  err_printf ("unimplemented kernel method TCB_SetSpace\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_SetTLSBase (cte_t *, word_t)
{
  err_printf ("unimplemented kernel method TCB_SetTLSBase\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_Suspend (cte_t *)
{
  err_printf ("unimplemented kernel method TCB_Suspend\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
TCB_WriteRegisters (cte_t *, bool, word_t, word_t, user_context_t *)
{
  err_printf ("unimplemented kernel method TCB_WriteRegisters\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
Untyped_Retype (cte_t *, word_t, word_t, cte_t *, word_t, uint8_t, word_t,
                word_t)
{
  err_printf ("unimplemented kernel method Untyped_Retype\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_In8 (cte_t *, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_In8\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_In16 (cte_t *, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_In16\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_In32 (cte_t *, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_In32\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_Out8 (cte_t *, word_t, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_Out8\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_Out16 (cte_t *, word_t, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_Out16\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPort_Out32 (cte_t *, word_t, word_t)
{
  err_printf ("unimplemented kernel method X86_IOPort_Out32\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_IOPortControl_Issue (cte_t *, word_t, word_t, cte_t *, word_t, uint8_t)
{
  err_printf ("unimplemented kernel method X86_IOPortControl_Issue\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_64_PDPT_Map (cte_t *, cte_t *, word_t, X86_VMAttributes_t)
{
  err_printf ("unimplemented kernel method X86_64_PDPT_Map\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_64_PDPT_Unmap (cte_t *)
{
  err_printf ("unimplemented kernel method X86_64_PDPT_Unmap\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_PD_Map (cte_t *, cte_t *, word_t, X86_VMAttributes_t)
{
  err_printf ("unimplemented kernel method X86_PD_Map\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_PD_Unmap (cte_t *)
{
  err_printf ("unimplemented kernel method X86_PD_Unmap\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_PT_Map (cte_t *, cte_t *, word_t, X86_VMAttributes_t)
{
  err_printf ("unimplemented kernel method X86_PT_Map\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_PT_Unmap (cte_t *)
{
  err_printf ("unimplemented kernel method X86_PT_Unmap\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_Page_Map (cte_t *, cte_t *, word_t, X86_VMAttributes_t)
{
  err_printf ("unimplemented kernel method X86_Page_Map\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
X86_Page_Unmap (cte_t *)
{
  err_printf ("unimplemented kernel method X86_Page_Unmap\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
IRQControl_get (cte_t *, word_t, cte_t *, word_t, uint8_t)
{
  err_printf ("unimplemented kernel method IRQControl_get\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
IRQHandler_Ack (cte_t *)
{
  err_printf ("unimplemented kernel method IRQHandler_Ack\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
IRQHandler_Clear (cte_t *)
{
  err_printf ("unimplemented kernel method IRQHandler_Clear\n");
  return illegal_operation;
}
__attribute__ ((weak)) message_info_t
IRQHandler_SetNotification (cte_t *, cte_t *)
{
  err_printf ("unimplemented kernel method IRQHandler_SetNotification\n");
  return illegal_operation;
}
