name: Build untitled

on: [ push ]

jobs:
  build-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install OS dependancies
        run: |
          sudo apt update
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository -y "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install git make cmake ninja-build ruby clang lld xorriso mtools qemu-system
      - name: build
        run: |
          mkdir -p build
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchains/x86_64.cmake
          cmake --build build
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: untitled_bare_metal.iso
          path: untitled_bare_metal.iso
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: untitled_bare_metal.iso

  # build-native:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Install OS dependancies
  #       run: |
  #         sudo apt update
  #         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  #         sudo add-apt-repository -y "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main"
  #         sudo apt-get update
  #         sudo apt-get upgrade
  #         sudo apt install git make cmake ninja-build ruby clang lld xorriso mtools qemu-system
  #     - name: build
  #       run: |
  #         mkdir -p build
  #         cmake -B build -DCMAKE_C_COMPILER=clang
  #         cmake --build build
