// This file is autogenerated by './gen'. Do not edit.

#pragma once

#include "sys/types.h"

enum object_type
{
  CAP_NULL,
  CAP_ENDPOINT,
  CAP_REPLY,
  CAP_NOTIFICATION,
  CAP_CNODE,
  CAP_TCB,
  CAP_UNTYPED,
  CAP_X86_64_IO_PORT,
  CAP_X86_64_IO_PORT_CONTROL,
  CAP_X86_64_PML4,
  CAP_X86_64_PDPT,
  CAP_X86_64_PD,
  CAP_X86_64_PT,
  CAP_X86_64_PAGE,
  CAP_X86_64_HUGE_PAGE,
  CAP_IRQ_CONTROL,
  CAP_IRQ_HANDLER,
  MAX_CAP_TYPE,
};

static inline const char *
cap_type_string (word_t type)
{
  switch (type)
    {
    case CAP_NULL:
      return "null";
    case CAP_ENDPOINT:
      return "endpoint";
    case CAP_REPLY:
      return "reply";
    case CAP_NOTIFICATION:
      return "notification";
    case CAP_CNODE:
      return "cnode";
    case CAP_TCB:
      return "tcb";
    case CAP_UNTYPED:
      return "untyped";
    case CAP_X86_64_IO_PORT:
      return "x86_64_io_port";
    case CAP_X86_64_IO_PORT_CONTROL:
      return "x86_64_io_port_control";
    case CAP_X86_64_PML4:
      return "x86_64_pml4";
    case CAP_X86_64_PDPT:
      return "x86_64_pdpt";
    case CAP_X86_64_PD:
      return "x86_64_pd";
    case CAP_X86_64_PT:
      return "x86_64_pt";
    case CAP_X86_64_PAGE:
      return "x86_64_page";
    case CAP_X86_64_HUGE_PAGE:
      return "x86_64_huge_page";
    case CAP_IRQ_CONTROL:
      return "irq_control";
    case CAP_IRQ_HANDLER:
      return "irq_handler";
    default:
      return "unknown";
    }
}

enum method_id
{
  METHOD_INVALID,
  METHOD_CNODE_COPY,
  METHOD_CNODE_DELETE,
  METHOD_CNODE_MINT,
  METHOD_CNODE_REVOKE,
  METHOD_CNODE_DEBUG_PRINT,
  METHOD_CNODE_DEBUG_GET,
  METHOD_TCB_CONFIGURE,
  METHOD_TCB_READ_REGISTERS,
  METHOD_TCB_RESUME,
  METHOD_TCB_BIND_NOTIFICATION,
  METHOD_TCB_SET_TLS_BASE,
  METHOD_TCB_SUSPEND,
  METHOD_TCB_WRITE_REGISTERS,
  METHOD_TCB_SET_DEBUG,
  METHOD_TCB_SET_NAME,
  METHOD_UNTYPED_RETYPE,
  METHOD_X86_64_IO_PORT_IN8,
  METHOD_X86_64_IO_PORT_IN16,
  METHOD_X86_64_IO_PORT_IN32,
  METHOD_X86_64_IO_PORT_OUT8,
  METHOD_X86_64_IO_PORT_OUT16,
  METHOD_X86_64_IO_PORT_OUT32,
  METHOD_X86_64_IO_PORT_CONTROL_ISSUE,
  METHOD_X86_64_PDPT_MAP,
  METHOD_X86_64_PD_MAP,
  METHOD_X86_64_PT_MAP,
  METHOD_X86_64_PAGE_MAP,
  METHOD_X86_64_HUGE_PAGE_MAP,
  METHOD_IRQ_CONTROL_GET,
  METHOD_IRQ_HANDLER_ACK,
  METHOD_IRQ_HANDLER_CLEAR,
  METHOD_IRQ_HANDLER_SET_NOTIFICATION,
};

enum error_code
{
  NO_ERROR,
  ALIGNMENT_ERROR,
  DELETE_FIRST,
  FAILED_LOOKUP,
  ILLEGAL_OPERATION,
  INVALID_ARGUMENT,
  INVALID_CAPABILITY,
  INVALID_SYSCALL,
  INVALID_ROOT,
  NOT_ENOUGH_MEMORY,
  RANGE_ERROR,
  REVOKE_FIRST,
  TRUNCATED_MESSAGE,
  UNKNOWN_MESSAGE,
  WOULD_BLOCK,
  MAX_ERROR_CODE,
};

static inline const char *
error_string (error_t error)
{
  switch (error)
    {
    case NO_ERROR:
      return "no error";
    case ALIGNMENT_ERROR:
      return "alignment error";
    case DELETE_FIRST:
      return "delete first";
    case FAILED_LOOKUP:
      return "failed lookup";
    case ILLEGAL_OPERATION:
      return "illegal operation";
    case INVALID_ARGUMENT:
      return "invalid argument";
    case INVALID_CAPABILITY:
      return "invalid capability";
    case INVALID_SYSCALL:
      return "invalid syscall";
    case INVALID_ROOT:
      return "invalid root";
    case NOT_ENOUGH_MEMORY:
      return "not enough memory";
    case RANGE_ERROR:
      return "range error";
    case REVOKE_FIRST:
      return "revoke first";
    case TRUNCATED_MESSAGE:
      return "truncated message";
    case UNKNOWN_MESSAGE:
      return "unknown message";
    case WOULD_BLOCK:
      return "would block";
    default:
      return "unknown";
    }
}

enum syscall_number
{
  SYS_EXIT,
  SYS_DEBUG_WRITE,
  SYS_CALL,
  SYS_YIELD,
  SYS_SEND,
  SYS_NBSEND,
  SYS_RECV,
  SYS_NBRECV,
  SYS_REPLY,
  SYS_REPLYRECV,
};
